spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    show-sql: false

logging:
  level:
    com.yhj.erp.user: DEBUG